Add input loading from stdin using pipes

diff --git a/type-train b/type-train
--- a/type-train
+++ b/type-train
@@ -25,7 +25,7 @@ expect_char() {
     local EXPECTED_CHAR="$1"
     local INVALID_INPUT_COUNT=0
     while [ 1 ]; do
-        IFS= read -s -r -n 1 ENTERED_CHAR
+        IFS= read -s -r -n 1 ENTERED_CHAR </dev/tty
         [ "$ENTERED_CHAR" == "$EXPECTED_CHAR" ] && break
         local INVALID_INPUT_COUNT=$((INVALID_INPUT_COUNT+1))
     done
@@ -33,8 +33,13 @@ expect_char() {
 }
 
 main() {
-    if [ "$@" ]; then
-        local TRAIN_TEXT="$@"
+    if [ ${#@} -gt 0 ]; then
+        if [ "$1" == "-f" ]; then
+            [ ! -f "$2" ] && echo "file not found: $2" 1>&2 && return 1
+            local TRAIN_TEXT="$(< "$2")"
+        else
+            local TRAIN_TEXT="$@"
+        fi
     else
         local TRAIN_TEXT="$(< /dev/stdin)" # stdin
     fi
@@ -42,17 +47,17 @@ main() {
     # echo colorized text and move cursor to beginning
     printf "${COLOR_NEW_TEXT}${TRAIN_TEXT}${COLOR_RESET}"
     for i in $(seq 1 ${#TRAIN_TEXT}); do printf '\b'; done
-
     # read input from user and print correct characters in other color
     printf "${COLOR_TYPED_TEXT}"
     local START_TIME=$(date +%s%N)
     local MISTAKES=0
-    while IFS= read -n 1 -u 10 CURRENT_CHAR; do
+    for ((i=0; i<${#TRAIN_TEXT}; i++)); do
+        local CURRENT_CHAR="${TRAIN_TEXT:$i:1}"
         [ "$CURRENT_CHAR" == "" ] && break # eof
         expect_char "$CURRENT_CHAR"
         printf "${CURRENT_CHAR}"
         local MISTAKES=$((MISTAKES+$?))
-    done 10<<< "$TRAIN_TEXT"
+    done
     local END_TIME=$(date +%s%N)
     local ELAPSED_TIME=$(((END_TIME - START_TIME)/1000000))
 
